const colors = {
  dark: {
    text:               "#ddeeff",
    tint:               "#3b8ef3",
    background:         "#060c18",
    foreground:         "#ddeeff",
    card:               "#0b1828",
    cardForeground:     "#ddeeff",
    primary:            "#3b8ef3",
    primaryForeground:  "#ffffff",
    secondary:          "#0e1e30",
    secondaryForeground:"#9ab8d8",
    muted:              "#0e1e30",
    mutedForeground:    "#4e7090",
    accent:             "#0e2040",
    accentForeground:   "#3b8ef3",
    destructive:        "#ef4444",
    destructiveForeground: "#ffffff",
    success:            "#10b981",
    successForeground:  "#ffffff",
    warning:            "#f59e0b",
    warningForeground:  "#ffffff",
    border:             "#142235",
    input:              "#0e1e30",
    overlay:            "rgba(0,0,0,0.8)",
  },

  light: {
    text:               "#0a0f1a",
    tint:               "#3b8ef3",
    background:         "#f4f7fb",
    foreground:         "#0a0f1a",
    card:               "#ffffff",
    cardForeground:     "#0a0f1a",
    primary:            "#3b8ef3",
    primaryForeground:  "#ffffff",
    secondary:          "#edf2f8",
    secondaryForeground:"#374151",
    muted:              "#edf2f8",
    mutedForeground:    "#6b7c93",
    accent:             "#dbeafe",
    accentForeground:   "#1d4ed8",
    destructive:        "#ef4444",
    destructiveForeground: "#ffffff",
    success:            "#10b981",
    successForeground:  "#ffffff",
    warning:            "#f59e0b",
    warningForeground:  "#ffffff",
    border:             "#e2eaf4",
    input:              "#edf2f8",
    overlay:            "rgba(0,0,0,0.4)",
  },

  radius: 14,
};

export default colors;
